[project]
name = "finm32500-assignment-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.11.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pytest>=8.4.2",
]
